export interface IArticlesForMyChannel{
    channelId: number,
    channelName: string,
    authorID: number,
    authorFullname: string,
    avatarChannelID: number,
    coverChannelID: number,
    arrPostsInChannel: any[],
    arrSubscriptionsInChannel: any[],
    arrKnowlegesParts: any[],
    arrTags: any[],
    arrComments: any[],
    viewMyPosts: boolean,
    setViewMyPosts: React.Dispatch<React.SetStateAction<boolean>>,
    viewMyComments: any,
    setViewMyComments: React.Dispatch<React.SetStateAction<boolean>>,
    createMyFirstPost: any,
    setCreateMyFirstPost: any,
    arrCountSubscriptionsChannels: number
}