export interface IBtnEditChannel{
    key: number,
    channelId: number,
    channelName: string;
    authorID: number,
    authorFullname: string,
    channelDecript: string,
    avatarChannelID: number,
    coverChannelID: number,
    arrPostsInChannel: any[],
    arrSubscriptionsInChannel: any[],
    arrKnowlegesParts: any[],
    arrTags: any[],
    arrComments: any[],
    arrCountSubscriptionsChannels: number,
    arrAuthors: any[],
    arrAllClassificators: any[],
    coverChannel: number,
    setCoverChannel: any,
    avatarChannel: number, 
    setAvatarChannel: any,
    channelAvatarDialog: boolean, 
    setChannelAvatarDialog: any,
    nameChannel: string,
    setNameChannel: any,
    descriptChannel: string,
    setDescriptChannel: any
}